### ISSUE TITLE
Muligheter for å ha alt i et repo

### ISSUE THREAD

**Issue by 594760** [Project-insert-name/root-website-frontend#37]
Etter å sett litt på det er jeg åpen for å flytte repoet til CMS en in i dette repoet eller begge inn i et nytt repo.

Ser at det kan gjøre flyten mellom enklere isteden for ha to separate repo.

Har dere noe tanker om det?

**Comment by emberal** [comment]
Ser ut til at vi får også fordelen med at sanity studio blir deployet sammen med resten av nettsiden på rootlinjeforening.no/studio
Da slipper vi å deploye hver av de separat

https://www.sanity.io/guides/nextjs-app-router-live-preview

**Comment by emberal** [comment]
#42
